### ISSUE TITLE
Please submit this to the main OpenStack Keystone project

### ISSUE THREAD

**Issue by admiyo** [SUSE-Cloud/keystone-hybrid-backend#42]
Enough people have requested it and are using it that it should at least be submitted, and the review process begun.

**Comment by matthewfischer** [comment]
+100. I'd love to stop maintaining my own fork for L and beyond. If we do this I'd like to figure out how to make some options to skip listing users from LDAP. We only want the user list from mysql because the LDAP list takes over 5 minutes to spit out and 99.99% of those people are not OpenStack users.
